name: release

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: react-editor-js-${{ hashFiles('**/yarn.lock') }}
      - run: npm install -g yarn
      - run: yarn
      - run: chmod -R +x ./node_modules/.bin
      - uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/download-artifact@v1
        with:
          name: node_modules
      - run: yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/download-artifact@v1
        with:
          name: dist
      - run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_ACCESS_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
